# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='account name')),
                ('code', models.CharField(max_length=32, verbose_name='account code')),
                ('password', models.CharField(max_length=32, verbose_name='account password')),
                ('fullname', models.CharField(max_length=128, verbose_name='company full name')),
                ('address', models.CharField(max_length=128, verbose_name='company address')),
                ('status', models.IntegerField(choices=[(0, 'enabled'), (1, 'disabled'), (2, 'expired')], verbose_name='account status')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='dep name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='emp name')),
                ('work_no', models.CharField(max_length=16, verbose_name='emp work no')),
                ('avatar', models.ImageField(upload_to='', verbose_name='emp avatar')),
                ('status', models.IntegerField(verbose_name='emp status')),
                ('mobile', models.CharField(max_length=20, verbose_name='emp mobile')),
                ('birthday', models.DateField(verbose_name='emp birthday')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.Company')),
                ('department', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hrm.Department')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeCert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'id'), (1, 'passport'), (2, 'other')])),
                ('number', models.CharField(max_length=128)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(verbose_name='end time')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.Company')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_head', to='hrm.Employee'),
        ),
    ]
