# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contact_email',
            field=models.CharField(default='', max_length=64, verbose_name='company email name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='contact_mobile',
            field=models.CharField(default='', max_length=16, verbose_name='company mobile name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='contact_name',
            field=models.CharField(default='', max_length=16, verbose_name='company contact name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(max_length=32, verbose_name='company code'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=128, verbose_name='company name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='password',
            field=models.CharField(max_length=32, verbose_name='company password'),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.IntegerField(choices=[(0, 'enabled'), (1, 'disabled'), (2, 'expired')], verbose_name='company status'),
        ),
    ]
