# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0002_auto_20160510_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed_time', models.DateTimeField(auto_created=True, verbose_name='installation time')),
                ('name', models.CharField(max_length=32, verbose_name='plugin name')),
                ('description', models.TextField(verbose_name='plugin description')),
                ('icon', models.ImageField(upload_to='', verbose_name='plugin icon')),
                ('unique_id', models.CharField(max_length=32, verbose_name='plugin unique id')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.Company')),
            ],
        ),
    ]
