# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(upload_to='', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birthday',
            field=models.DateField(verbose_name='birthday'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.CharField(max_length=20, verbose_name='mobile'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=16, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.IntegerField(choices=[(0, 'JOINED'), (1, 'LEAVED'), (2, 'INACTIVE')], default=0, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_no',
            field=models.CharField(max_length=16, verbose_name='work no'),
        ),
    ]
