# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160512_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='company code')),
                ('work_no', models.CharField(max_length=16, verbose_name='work no')),
                ('password', models.CharField(max_length=32, verbose_name='password')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
            },
        ),
    ]
