# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 11:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160512_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['updated_at', '-status'], 'verbose_name': 'company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='creation_time',
        ),
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 12, 11, 20, 28, 308757, tzinfo=utc), verbose_name='creation time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 12, 11, 20, 34, 537114, tzinfo=utc), verbose_name='update time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(null=True, upload_to='', verbose_name='avatar'),
        ),
    ]
